services:
  - type: web
    name: flask test
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /test
    envVars:
      - key: FLASK_ENV
        value: productio